### ISSUE TITLE
Deprecate settle?

### ISSUE THREAD

**Issue by 1j01** [divshot/broker#1]
So I tried installing and using `settle` and it got an error (`Error: Cannot find module 'hyperquest'`)
So I went to open an issue on the repo and it redirected to this repo,
with a new name and new version without the error...
Maybe you should [deprecate](https://docs.npmjs.com/cli/deprecate) `settle`?

**Comment by scottcorgan** [comment]
Deprecation message on NPM now. Thanks for the heads up!
